language: java

sudo: required

services:
  - docker


after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker build -t echosoft/taxi .;
    docker push echosoft/taxi;
    fi
