version: '3'
services:
  taxi:
    container_name: taxi
    image: 'echosoft/taxi'
    build: .
    ports:
     - "4567:4567"
    environment:
      - ELASTICSEARCH_API=http://elasticsearch:9200
    links:
      - elasticsearch
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:5.6.3"
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200